CREATE DATABASE E_COMMERCE_DB;
USE E_COMMERCE_DB;

CREATE TABLE CUSTOMERS (                            -- 
    CUSTOMER_ID INT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(50) NOT NULL,     
    PHONE VARCHAR(15),
    CITY VARCHAR(20) DEFAULT 'CHENNAI'
);

CREATE TABLE EMPLOYEES (                      -- EMPLOYEES
    EMPLOYEE_ID INT PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR(50) NOT NULL,
    POSITION VARCHAR(30),
    MANAGER_ID INT,
    SALARY DECIMAL(10,2),
    FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

CREATE TABLE SHIPPERS (                         -- SHIPPERS
    SHIPPER_ID INT PRIMARY KEY,
    SHIPPER_NAME VARCHAR(50),
    PHONE VARCHAR(15)
);

CREATE TABLE CATEGORIES (                       -- CATEGORIES
    CATEGORY_ID INT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE SUPPLIERS (                       -- SUPPLIERS
    SUPPLIER_ID INT PRIMARY KEY,
    SIPPLIER_NAME VARCHAR(50) NOT NULL,
    CITY VARCHAR(50),
    COUNTRY VARCHAR(40)
);

CREATE TABLE PRODUCTS (                       -- PRODUCTS
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(50) NOT NULL,
    CATEGORY_ID INT,
    SUPPLIER_ID INT,
    PRICE DECIMAL(10,2),
    STOCK INT,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID),
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID)
);
CREATE TABLE ORDERS (                   -- ORDERS
    ORDER_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    EMPLOYEE_ID INT,
    SHIPPER_ID INT,
    ORDER_DATE DATE,
    Status VARCHAR(30),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
    FOREIGN KEY (SHIPPER_ID) REFERENCES SHIPPERS(SHIPPER_ID)
);

CREATE TABLE ORDERITEMS (                            -- ORDER ITEMS
    ORDERITEM_ID INT PRIMARY KEY,
    ORDER_ID INT,
    PRODUCT_ID INT,
    QUANTITY INT,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

INSERT INTO CATEGORIES VALUES               -- INSERT CATEGORIES
(1,'ELECTRONICS'),
(2,'FURNITURE'),
(3,'CLOTHING'),
(4,'GROCERIES'),
(5,'SPORTS');

INSERT INTO SUPPLIERS VALUES                          -- INSERT SUPPLIERS
(101,'TECH WORLD','CHENNAI','INDIA'),
(102,'HOME NEEDS','BANGALORE','INDIA'),
(103,'FASHION HUB','MUMBAI','INDIA'),
(104,'FRESH MART','HYDERABAD','INDIA'),
(105,'SPORT ZONE','DELHI','INDIA');

INSERT INTO PRODUCTS VALUES                   -- INSERT PRODUCTS
(201,'LAPTOP',1,101,65000,20),
(202,'SMARTPHONE',1,101,25000,50),
(203,'OFFICE CHAIR',2,102,5000,30),
(204,'DINING TABLE',2,102,12000,15),
(205,'T-SHIRT',3,103,800,100),
(206,'JEANS',3,103,1500,80),
(207,'RICE BAG',4,104,1200,40),
(208,'COOKING OIL',4,104,1800,35),
(209,'FOOTBALL',5,105,900,60),
(210,'CRICKET BAT',5,105,2500,25);

INSERT INTO CUSTOMERS VALUES                         -- INSERT CUSTOMERS
(301,'Arun Kumar','9876543210','Chennai'),
(302,'Meena Devi','9876543211','Coimbatore'),
(303,'Suresh Babu','9876543212','Madurai'),
(304,'Divya Sri','9876543213','Salem'),
(305,'Karthik Raj','9876543214','Trichy');

INSERT INTO EMPLOYEES VALUES                          -- INSERT EMPLOYEES
(401,'Rajesh','Manager',NULL,70000),
(402,'Anand','Sales Executive',401,35000),
(403,'Priya','Sales Executive',401,36000),
(404,'Vijay','Warehouse Staff',401,28000),
(405,'Keerthi','Support Staff',401,30000);

INSERT INTO SHIPPERS VALUES                     -- INSERT SHIPPERS
(501,'Blue Dart','9876500001'),
(502,'DTDC','9876500002'),
(503,'Delhivery','9876500003');

INSERT INTO ORDERS VALUES                       -- INSERT ORDERS
(601,301,402,501,'2026-07-01','Delivered'),
(602,302,403,502,'2026-07-02','Shipped'),
(603,303,402,503,'2026-07-03','Pending'),
(604,304,405,501,'2026-07-04','Delivered'),
(605,305,403,502,'2026-07-05','Processing');

INSERT INTO ORDERITEMS VALUES                  -- INSERT ORDER ITEMS
(701,601,201,1),
(702,601,205,2),
(703,602,202,1),
(704,602,209,2),
(705,603,203,1),
(706,603,207,3),
(707,604,210,1),
(708,604,208,2),
(709,605,204,1),
(710,605,206,2);

SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,O.ORDER_ID FROM CUSTOMERS C   
INNER JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID;

SELECT C.CUSTOMER_NAME ,O.ORDER_ID FROM ORDERS O 
INNER JOIN CUSTOMERS C ON C.CUSTOMER_ID=O.CUSTOMER_ID;

SELECT P.PRODUCT_ID,P.PRODUCT_NAME,C.CATEGORY_ID,C.CATEGORY_NAME FROM PRODUCTS P
LEFT JOIN CATEGORIES C ON P.CATEGORY_ID=C.CATEGORY_ID;

SELECT P.PRODUCT_ID,P.PRODUCT_NAME,S.SUPPLIER_NAME FROM PRODUCTS P 
INNER JOIN  SUPPLIERS S ON P.SUPPLIER_ID = S.SUPPLIER_ID;

SELECT O.ORDER_ID,E.EMPLOYEE_ID FROM ORDERS O 
LEFT JOIN EMPLOYEES E ON O.EMPLOYEE_ID=E.EMPLOYEE_ID;

SELECT O.ORDER_ID,S.SHIPPER_NAME FROM ORDERS O 
RIGHT JOIN SHIPPERS S ON O.SHIPPER_ID = S.SHIPPER_ID;

SELECT C.CUSTOMER_ID,COUNT(O.ORDER_ID) AS TOTAL_ORDERS FROM CUSTOMERS C 
INNER JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID
HAVING COUNT(O.ORDER_ID)>=1;

SELECT O.ORDER_ID,P.PRODUCT_NAME,QI.QUANTITY FROM ORDERS O 
JOIN ORDERITEMS QI ON O.ORDER_ID=QI.ORDER_ID JOIN PRODUCTS P 
ON QI.PRODUCT_ID-P.PRODUCT_ID ORDER BY O.ORDER_ID;

SELECT P.PRODUCT_NAME ,OI.QUANTITY FROM PRODUCTS P 
JOIN ORDERITEMS OI ON P.PRODUCT_ID=OI.PRODUCT_ID;

SELECT E.EMPLOYEE_NAME,C.CUSTOMER_NAME FROM ORDERS O 
JOIN EMPLOYEES E ON O.EMPLOYEE_ID=E.EMPLOYEE_ID
JOIN CUSTOMERS C ON O.CUSTOMER_ID=C.CUSTOMER_ID;

SELECT C.CUSTOMER_NAME,O.ORDER_ID,P.PRODUCT_NAME,OI.QUANTITY,P.PRICE FROM CUSTOMERS C JOIN ORDERS O 
ON C.CUSTOMER_ID=O.CUSTOMER_ID JOIN ORDERITEMS OI ON O.ORDER_ID=OI.ORDER_ID
JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID;

SELECT S.SUPPLIER_NAME,P.PRODUCT_NAME FROM SUPPLIERS S
JOIN PRODUCTS P ON S.SUPPLIER_ID = P.SUPPLIER_ID
JOIN ORDERITEMS OI ON P.PRODUCT_ID = OI.PRODUCT_ID;

SELECT C.CATEGORY_NAME,COUNT(P.PRODUCT_ID) AS PRODUCT_COUNT
FROM CATEGORIES C LEFT JOIN PRODUCTS P
ON C.CATEGORY_ID = P.CATEGORY_ID GROUP BY C.CATEGORY_NAME;

SELECT C.CUSTOMER_NAME,COUNT(O.ORDER_ID) AS TOTAL_ORDERS
FROM CUSTOMERS C LEFT JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID GROUP BY C.CUSTOMER_NAME;

SELECT E.EMPLOYEE_NAME,SUM(OI.QUANTITY * P.PRICE) AS TOTAL_SALES FROM EMPLOYEES E
JOIN ORDERS O ON E.EMPLOYEE_ID = O.EMPLOYEE_ID
JOIN ORDERITEMS OI ON O.ORDER_ID = OI.ORDER_ID
JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
GROUP BY E.EMPLOYEE_NAME;

SELECT C.CATEGORY_NAME,SUM(OI.QUANTITY * P.PRICE) AS REVENUE
FROM CATEGORIES C
JOIN PRODUCTS P ON C.CATEGORY_ID = P.CATEGORY_ID
JOIN ORDERITEMS OI ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY C.CATEGORY_NAME;

SELECT C.CATEGORY_NAME,P.PRODUCT_NAME,P.PRICE FROM PRODUCTS P
JOIN CATEGORIES C ON P.CATEGORY_ID = C.CATEGORY_ID
WHERE P.PRICE =(SELECT MAX(P2.PRICE)FROM PRODUCTS P2
WHERE P2.CATEGORY_ID = P.CATEGORY_ID);

SELECT P.PRODUCT_NAME FROM PRODUCTS P
LEFT JOIN ORDERITEMS OI ON P.PRODUCT_ID = OI.PRODUCT_ID
WHERE OI.PRODUCT_ID IS NULL;

SELECT C.CUSTOMER_NAME FROM CUSTOMERS C
LEFT JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE O.ORDER_ID IS NULL;

SELECT S.SUPPLIER_NAME FROM SUPPLIERS S
LEFT JOIN PRODUCTS P ON S.SUPPLIER_ID = P.SUPPLIER_ID
WHERE P.PRODUCT_ID IS NULL;

SELECT C.CUSTOMER_NAME,SUM(OI.QUANTITY * P.PRICE) AS SPENDING FROM CUSTOMERS C
JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN ORDERITEMS OI ON O.ORDER_ID = OI.ORDER_ID
JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
GROUP BY C.CUSTOMER_NAME
ORDER BY SPENDING DESC
LIMIT 5;

SELECT E.EMPLOYEE_NAME,MONTH(O.ORDER_DATE) AS MONTH,SUM(OI.QUANTITY * P.PRICE) AS SALES
FROM EMPLOYEES E
JOIN ORDERS O ON E.EMPLOYEE_ID = O.EMPLOYEE_ID
JOIN ORDERITEMS OI ON O.ORDER_ID = OI.ORDER_ID
JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
GROUP BY E.EMPLOYEE_NAME, MONTH(O.ORDER_DATE);

SELECT P.PRODUCT_NAME,SUM(OI.QUANTITY) AS TOTAL_SOLD FROM PRODUCTS P
JOIN ORDERITEMS OI ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.PRODUCT_NAME
ORDER BY TOTAL_SOLD DESC
LIMIT 1;

SELECT S.SUPPLIER_NAME,SUM(OI.QUANTITY * P.PRICE) AS REVENUE FROM SUPPLIERS S
JOIN PRODUCTS P ON S.SUPPLIER_ID = P.SUPPLIER_ID
JOIN ORDERITEMS OI ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY S.SUPPLIER_NAME;

SELECT C.CUSTOMER_NAME,AVG(OI.QUANTITY * P.PRICE) AS AVG_ORDER_VALUE FROM CUSTOMERS C
JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN ORDERITEMS OI ON O.ORDER_ID = OI.ORDER_ID
JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
GROUP BY C.CUSTOMER_NAME;

SELECT ORDER_ID,COUNT(PRODUCT_ID) AS PRODUCT_COUNT FROM ORDERITEMS
GROUP BY ORDER_ID
HAVING COUNT(PRODUCT_ID) > 3;

SELECT C.CUSTOMER_NAME,COUNT(DISTINCT P.CATEGORY_ID) AS CATEGORY_COUNT FROM CUSTOMERS C
JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN ORDERITEMS OI ON O.ORDER_ID = OI.ORDER_ID
JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
GROUP BY C.CUSTOMER_NAME
HAVING COUNT(DISTINCT P.CATEGORY_ID) > 1;

SELECT C.CATEGORY_NAME FROM CATEGORIES C
LEFT JOIN PRODUCTS P ON C.CATEGORY_ID = P.CATEGORY_ID
LEFT JOIN ORDERITEMS OI ON P.PRODUCT_ID = OI.PRODUCT_ID
WHERE OI.PRODUCT_ID IS NULL;

SELECT O.ORDER_ID,SUM(OI.QUANTITY * P.PRICE) AS ORDER_VALUE FROM ORDERS O
JOIN ORDERITEMS OI ON O.ORDER_ID = OI.ORDER_ID
JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
GROUP BY O.ORDER_ID
ORDER BY ORDER_VALUE DESC
LIMIT 1;

SELECT C.CUSTOMER_NAME,
       O.ORDER_ID,
       O.ORDER_DATE,
       E.EMPLOYEE_NAME,
       S.SHIPPER_NAME,
       P.PRODUCT_NAME,
       CA.CATEGORY_NAME,
       SU.SUPPLIER_NAME,
       OI.QUANTITY,
       P.PRICE,
       (OI.QUANTITY * P.PRICE) AS TOTAL_AMOUNT
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN EMPLOYEES E
ON O.EMPLOYEE_ID = E.EMPLOYEE_ID
JOIN SHIPPERS S
ON O.SHIPPER_ID = S.SHIPPER_ID
JOIN ORDERITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
JOIN PRODUCTS P
ON OI.PRODUCT_ID = P.PRODUCT_ID
JOIN CATEGORIES CA
ON P.CATEGORY_ID = CA.CATEGORY_ID
JOIN SUPPLIERS SU
ON P.SUPPLIER_ID = SU.SUPPLIER_ID
ORDER BY O.ORDER_ID;