CREATE DATABASE JOIN_S;
USE JOIN_S;

CREATE TABLE S_STUDENT(
	STUDENT_ID INT,
    STUDENT_NAME VARCHAR(50)
    );
    
    CREATE TABLE E_ENTROLLMENT(
		STUDENT_ID INT,
        COURSE_ID INT,
        COURSE_NAME VARCHAR(20)
        );
        
INSERT INTO S_STUDENT VALUES
(1,'VISHNU'),
(2,'PRIYA'),
(3,'NITHIYA'),
(4,'SANDHIYA'),
(5,'PAVI');
SELECT * FROM S_STUDENT;

INSERT INTO E_ENTROLLMENT VALUES
(1,101,'PYTHON'),
(2,102,'SQL'),
(3,103,'JAVA'),
(1,104,'DSA');
SELECT * FROM E_ENTROLLMENT;

SELECT S.STUDENT_ID,E.COURSE_NAME FROM S_STUDENT S
INNER JOIN E_ENTROLLMENT E ON S.STUDENT_ID=E.STUDENT_ID;          -- inner join

SELECT S.STUDENT_ID,E.COURSE_NAME FROM S_STUDENT S
LEFT JOIN E_ENTROLLMENT E ON S.STUDENT_ID=E.STUDENT_ID;           -- left join

SELECT S.STUDENT_ID,E.COURSE_NAME FROM S_STUDENT S
RIGHT JOIN E_ENTROLLMENT E ON S.STUDENT_ID=E.STUDENT_ID;          -- right join

SELECT S.STUDENT_ID,E.COURSE_NAME FROM S_STUDENT S
LEFT JOIN E_ENTROLLMENT E ON S.STUDENT_ID=E.STUDENT_ID;           
UNION                                                             -- union
SELECT S.STUDENT_ID,E.COURSE_NAME FROM S_STUDENT S
RIGHT JOIN E_ENTROLLMENT E ON S.STUDENT_ID=E.STUDENT_ID;